### ISSUE TITLE
Some Problems with the Latest Version

### ISSUE THREAD

**Issue by CCCClear** [Globox1997/Dehydration#31]
It's me again. After all, this mod has a strong correlation with the EnvironmentZ mod.
After trying the latest version, I found the following problems:
Firstly, there is no direct purification method for the flasks, which makes flasks meaningless in front of stackable bottles. 
What's more, the purified water formula provided by the brewing stand has no use on the flasks.
Secondly, when there is a stackable mod, adding water to the campfire cauldron with bottles will cause the stacked bottles to become one.
Finally, when the purified water is poured into the campfire cauldron with the campfire not lit, the water will be unpurified.
Above, I hope my test can help you improve the mod.

**Comment by CCCClear** [comment]
I also found that the diamond leather flask and the netherite leather flask had the same capacity.

**Comment by Gappysona** [comment]
> Finally, when the purified water is poured into the campfire cauldron with the campfire not lit, the water will be unpurified.
Above, I hope my test can help you improve the mod.

NAB. Please post each individual bug separately next time, it would be much appreciated.

**Comment by Gappysona** [comment]
We will resolve this issue and might look into making purification a blockstate system (undetermined).

**Comment by Globox1997** [comment]
Actually no need to open multiple issues :)
To get purified water, you have fill the flasks or bottles at the campfire cauldron which now takes 5 seconds by default to get purified when the fire is lit. I actually don't care too much about the stackable mod because in my opinion it's op but the latest update may fixed this bug. As far as I know, you can fill the cauldron with purified water?
The netherite flask has intentionally no bigger capacity cause it's fire resistant :)
