### ISSUE TITLE
Slightly inconsistent behavior between dispensers and campfire cauldrons

### ISSUE THREAD

**Issue by colby-boucher** [Globox1997/Dehydration#47]
It's a bit hard to explain what's happening here in a consistent way, because it seems fairly inconsistent to me at the moment.

If you have a bucket of water in a dispenser with an empty campfire cauldron in front of it and activate the dispenser, great, you've got a filled campfire cauldron.

*Sometimes*, though, and this seems to only happen once there's a mix of empty and full buckets in the dispenser, sometimes, despite the cauldron being empty, the dispenser will spit out the bucket of water rather than filling the cauldron.

As far as I can tell this only happens when there's multiple full buckets *and* some empty buckets in the dispenser.

I thought hey, maybe this is just the Minecraft dispenser being weird since it dispenses things from a random slot, but the closest vanilla equivalent to this functionality is having a dispenser just dispense water _into_ a water source block (since you can't directly dispense water into cauldrons). Can't recreate this iffy behavior in that scenario, even once the dispenser starts spitting empty buckets, it'll only ever dispense the water and not the whole water bucket.

Edit: Here's a [short clip](https://vimeo.com/602318449) demonstrating what I'm talking about, see how a water bucket comes out at the end even though the cauldron is empty?

**Comment by Anhelm** [comment]
[crash-2021-09-21_09.14.15-client.txt](https://github.com/Globox1997/Dehydration/files/7199834/crash-2021-09-21_09.14.15-client.txt)
In addition to the above, here is the log of this error.

**Comment by Globox1997** [comment]
This is probably not the log of the bug @colby-boucher explained, however the dispenser bug is really odd since the function I use seems pretty save, can be found here [https://github.com/Globox1997/Dehydration/blob/master/src/main/java/net/dehydration/mixin/DispenserBlockMixin.java](https://github.com/Globox1997/Dehydration/blob/master/src/main/java/net/dehydration/mixin/DispenserBlockMixin.java)

After some investigation I think I found the issue :)
Fixed with [https://github.com/Globox1997/Dehydration/commit/8ee05438f49cb6e2227fe13a62563635d2cc508c](https://github.com/Globox1997/Dehydration/commit/8ee05438f49cb6e2227fe13a62563635d2cc508c)
