### ISSUE TITLE
Incompatible license

### ISSUE THREAD

**Issue by realguyman** [Globox1997/Dehydration#85]
Dehydration is licensed under GPLv3, a license which isn't compatible with Minecraft.

> Typically, when a copyleft license is wanted, the [GPL-3.0](https://spdx.org/licenses/GPL-3.0-only.html) or [AGPL-3.0](https://spdx.org/licenses/AGPL-3.0-only.html) would be used. However, these licenses are incompatible if linking into Minecraft, due to an issue with the difference between proprietary and free software outlined by these licenses (more information [here](https://www.gnu.org/licenses/gpl-faq.html#GPLPlugins)). An exception can be added to allow linking, such as that found [here](https://gist.github.com/wafflecoffee/588f353802a3b0ea649e4fc85f75e583), but it is recommended to just use the LGPL-3.0 instead if possible.

Source: https://blog.modrinth.com/licensing-guide/

**Comment by realguyman** [comment]
A very similar, yet compatible license is LGPLv3. @Globox1997 Please consider re-licensing the project under LGPLv3, as you are the copyright holder (which I'm assuming here, since you don't provide a copyright notice). No one else can re-license the project under an incompatible license because everyone else isn't a copyright holder of your project.

This isn't just a problem with Dehydration, though. It's also all of your projects that are licensed under GPL.

**Comment by Globox1997** [comment]
Hey realguyman,
I've read this blog post some time ago too but here is my opinion about it:

Luckily the disclaimer on this post says "We are not lawyers" otherwise I would believe what they say about the GPLv3 license.
One of the most famous open source repositories is the bukkit repo which is licensed under GPLv3 and even bought later by Mojang itself and still has the same license type. 

I'm not really interested in license stuff but of course don't want to get in trouble with it but changing a license is kinda meh.
LGPLv3 is mainly used for libraries but since the bukkit repo is gpl I have no issue with my decision for going gpl too.

Definitely open for your thoughts :)

**Comment by Globox1997** [comment]
Anymore thoughts? :)

**Comment by Globox1997** [comment]
Reopen with more thoughts
