### ISSUE TITLE
Small suggestions

### ISSUE THREAD

**Issue by Kisonu** [Globox1997/Dehydration#90]
Most thirst/temperature mods I've personally played around with include a block which collects rainwater which is by default, purified. I'd love to see a block like this added, or perhaps the rain catcher functionality could be added to the copper cauldron if it has sky access and its raining?
Another feature I'd love to see is the ability for dripstone to fill copper cauldrons with purified water. 

other ideas that would be cool could include -
The ability to place "purified water" down as a source block, as currently, filling a bucket with purified water converts it into regular water, which is unfortunate...
If you wanted to add environment to the world, you could set up some small world-gen feature that adds hot-springs filled with purified water as well, though that may be beyond the scope of this project. XD

**Comment by Globox1997** [comment]
Hey Kisonu, the rain catcher functionality is already implemented within the copper cauldron, I will increase the chance with the next update. The dropstone mechanic is also implemented.
My goal is to implement a well block with a later update. 
Buckets can't keep purified water since purified water isn't an own water block.
a world gen feature sounds cool but I want to keep it without since it might lead to update issues.
thanks for all the suggestions :)

**Comment by Kisonu** [comment]
Sounds great. Somehow I missed that functionality with the copper cauldron. Looking really forward to that well block! Thanks for the reply!!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Globox1997** [comment]
Some of the ideas got added in a later update.
