### ISSUE TITLE
Travelers Backpack Support

### ISSUE THREAD

**Issue by ardissaps** [Globox1997/Dehydration#92]
https://github.com/Tiviacz1337/Travelers-Backpack/issues/446

**Comment by Globox1997** [comment]
Dehydration provides an API here: [https://github.com/Globox1997/Dehydration/blob/1.19/src/main/java/net/dehydration/api/DrinkEvent.java](https://github.com/Globox1997/Dehydration/blob/1.19/src/main/java/net/dehydration/api/DrinkEvent.java)

**Comment by jmadarg** [comment]
Hi! 
Wanted to revive this issue, the dev of traveler's backpack says they need a Maven repo to add it to their dev environment
https://github.com/Tiviacz1337/Travelers-Backpack/issues/446#issuecomment-1475337017

**Comment by Tiviacz1337** [comment]
Hello, I'm a developer of Traveler's Backpack. I'd like to add compatibility with Dehydration mod, but I'm slightly confused about hydration values that would be added on drinking fluids.
If you could help me with that I'd be glad since I want to make compat that would work in a similiar way like in original mod.
Basically I'd like to add hydration to following fluids:
Regular water (1 Bucket on drink)
Purified water (1 Bucket on drink)
Potions (1 Bottle on drink)
Milk (1 Bucket on drink)
I'd need hydration values of that fluids that are used when players drink those fluids from regular items

**Comment by Tiviacz1337** [comment]
any update on this?

**Comment by Globox1997** [comment]
Sorry for the late response.
There are no values for buckets  but you can look into here for a feel how much water an item gives:
[https://github.com/Globox1997/Dehydration/blob/1.20/src/main/resources/data/dehydration/hydration_items/vanilla_items.json](https://github.com/Globox1997/Dehydration/blob/1.20/src/main/resources/data/dehydration/hydration_items/vanilla_items.json)
milk has 8 which is a lot and a potion 2.

**Comment by creeloper27** [comment]
Would get fixed if #159 gets merged.
